# Generated by Django 5.0.6 on 2024-08-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfig',
            name='default_from_email',
            field=models.EmailField(default='your-email@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='host',
            field=models.CharField(default='smtp.example.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='host_password',
            field=models.CharField(default='your-password', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='host_user',
            field=models.EmailField(default='your-email@example.com', max_length=254),
        ),
    ]
