# Generated by Django 5.0.6 on 2024-08-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kyc_status',
            field=models.CharField(default='Not Verified', max_length=20),
        ),
    ]
