# Generated by Django 5.0.6 on 2024-09-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CableRecharegAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(default='apiname', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('provider', models.CharField(default='https://example.com', max_length=1000)),
                ('api_url', models.TextField(default='https://apiname.online/api/cable', max_length=1000)),
                ('identifier', models.CharField(default='startimes', help_text='this should be a unique identifier', max_length=50)),
                ('service_id', models.CharField(default='waec_airtime', help_text='this should be a unique identifier', max_length=50)),
                ('agent_discount', models.FloatField(default=0.0, help_text="<strong style='color:red;'>This shoulg be a percentage of the amount the user buys</strong>")),
                ('user_discount', models.FloatField(default=0.0, help_text="<strong style='color:red;'>This shoulg be a percentage of the amount the user buys</strong>")),
                ('referrer_bonus', models.FloatField(default=0.0, help_text="<strong style='color:red;'>This shoulg be a percentage of the amount the user buys</strong>")),
                ('vtoken', models.CharField(default='Basic XXXXXXXXXX', help_text='this should be a unique identifier', max_length=100)),
                ('htoken', models.CharField(default='Basic XXXXXXXXXXX', help_text='this should be a unique identifier', max_length=100)),
                ('cable_image', models.ImageField(default='', help_text='the best image needed here is a square image recommended is 49 x 49px', upload_to='')),
                ('cable_type_price', models.TextField(default='["|select a DSTV package", "ACSSE36|DStv Access = N2000 + Convinience fee N50|2050|2050", "FTAE36|DStv FTA Plus = N1600 + Convinience fee N50|1650|1650", "COFAME36|DStv Family = N4000 + Convinience fee N50|4050|4050", "ASIAE36|DstvAsiaBouqet = N5400 + Convinience fee N50|5450|5450", "COMPE36|DStv Compact = N6800 + Convinience fee N50|6850|6850", "COMPLE36|DStv Plus = N10650 + Convinience fee N50|10700|10700", "PRWE36|Dstv Premium = N15800 + Convinience fee N50|15850|15850", "DPRHD|DStv Premium Asia Ex= N19900 + Convinience fee N50|19950|19950", "DPRHDP|Dstv Premium Extra = N18000 + Convinience fee N50|18050|18050"]', help_text='<span class="text-danger">["api_code|what_user_sees|api_price|site_price|site_service_code"]</span>', max_length=13000)),
                ('success_code', models.CharField(default='true', max_length=500)),
                ('description', models.TextField(default='<h4 id="note"><strong><u>How to Top-Up Airtime</u></strong></h4><p>TOP-UP your MTN, 9MOBILE, AIRTEL, GLO</p><p><li>Choose your Network</li><li>Enter your Recharge Amount</li><li>Enter the Phone number to recharge</li></p><p><strong>The more you recharge, the more bonus point you gathered</strong></p>', help_text='Html is allowed here')),
            ],
            options={
                'verbose_name': 'API For Cable Recharge',
                'verbose_name_plural': 'APIs For Cable Recharge',
            },
        ),
        migrations.CreateModel(
            name='DataNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(default='apiname', max_length=30)),
                ('provider', models.CharField(default='https://example.com', max_length=1000)),
                ('is_active', models.BooleanField(default=False)),
                ('network_image', models.ImageField(default='', help_text='the best image needed here is a square image recommended is 49 x 49px', upload_to='')),
                ('identifier', models.CharField(default='waec_airtime', help_text='this should be a unique identifier', max_length=50)),
                ('api_url', models.TextField(default='https://apiname.online/api/databundle', max_length=1000)),
                ('api_url_data', models.JSONField(default=dict, help_text='e.g: copy and paste this => {"data":{"apikey":"[YOUR_API_KEY]", "userid":"[USER_ID]", "network_id":"[urlvariable]", "amount":"[apiamount]", "datacode":"[dataplan]","phoneno":"[phone]"}, "headers":{"authorization":"Bearer API_KEY"}}, then edit suit you')),
                ('api_url_balance', models.TextField(default='https://apiname.online/api/balance?userid=[Enter_userid]&apikey=[Apikey]', max_length=1000)),
                ('success_code', models.CharField(default='true', max_length=500)),
                ('network_data_amount_json', models.TextField(default='220|500MB_(SME)|1|500MB (SME)@NGN220|extravariable,410|1GB_(SME)|1|1GB (SME)@NGN410|extravariable', help_text="<strong style='color:red;'>apiamount|data_amount|portal_api_code|what_user_sees|extravariable'</strong>", max_length=13000)),
                ('description', models.TextField(default='<h4 id="note"><strong><u>How to Top-Up Airtime</u></strong></h4><p>TOP-UP your MTN, 9MOBILE, AIRTEL, GLO</p><p><li>Choose your Network</li><li>Enter your Recharge Amount</li><li>Enter the Phone number to recharge</li></p><p><strong>The more you recharge, the more bonus point you gathered</strong></p>', help_text='Html is allowed here')),
            ],
            options={
                'verbose_name': 'API For Data Recharge',
                'verbose_name_plural': 'APIs For Data Recharge',
            },
        ),
        migrations.CreateModel(
            name='DataPlansPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtn', models.TextField(blank=True, default='', max_length='1000', null=True)),
                ('airtel', models.TextField(blank=True, default='', max_length='1000', null=True)),
                ('glo', models.TextField(blank=True, default='', max_length='1000', null=True)),
                ('nine_mobile', models.TextField(blank=True, default='', max_length='1000', null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RechargeAirtimeAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(default='apiname', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('network_image', models.ImageField(default='', help_text='the best image needed here is a square image recommended is 49 x 49px', upload_to='')),
                ('identifier', models.CharField(default='waec_airtime', help_text='this should be a unique identifier', max_length=50)),
                ('api_url', models.TextField(default='https://apiname.online/api/airtime', max_length=1000)),
                ('api_url_data', models.JSONField(default=dict, help_text='e.g: copy and paste this => {"data":{"apikey":"[YOUR_API_KEY]", "userid":"[USER_ID]", "network_id":"[network_code]", "amount":"[amt]", "phoneno":"[phone]"}, "headers":{"authorization": "Bearer (API_KEY)"}}, then edit suit you')),
                ('api_url_balance', models.TextField(default='https://apiname.online/api/balance?userid=[Enter_userid]&apikey=[Apikey]', max_length=1000)),
                ('user_discount', models.FloatField(default=0.0, help_text="<strong style='color:red;'>This shoulg be a percentage of the amount the user buys</strong>")),
                ('success_code', models.CharField(default='true', max_length=500)),
                ('description', models.TextField(default='<h4 id="note"><strong><u>How to Top-Up Airtime</u></strong></h4><p>TOP-UP your MTN, 9MOBILE, AIRTEL, GLO</p><p><li>Choose your Network</li><li>Enter your Recharge Amount</li><li>Enter the Phone number to recharge</li></p><p><strong>The more you recharge, the more bonus point you gathered</strong></p>', help_text='Html is allowed here')),
            ],
            options={
                'verbose_name': 'API For Airtime Recharge',
                'verbose_name_plural': 'APIs For Airtime Recharge',
            },
        ),
    ]
