# Generated by Django 5.0.6 on 2024-07-29 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rechargeairtimeapi',
            name='provider',
        ),
    ]
