# Generated by Django 5.0.6 on 2024-08-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_remove_rechargeairtimeapi_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cablerecharegapi',
            name='api_url_balance',
        ),
        migrations.RemoveField(
            model_name='cablerecharegapi',
            name='api_url_data',
        ),
        migrations.RemoveField(
            model_name='cablerecharegapi',
            name='customerCheck',
        ),
        migrations.RemoveField(
            model_name='cablerecharegapi',
            name='res_params',
        ),
        migrations.RemoveField(
            model_name='cablerecharegapi',
            name='successCheckCode',
        ),
        migrations.AddField(
            model_name='cablerecharegapi',
            name='agent_discount',
            field=models.FloatField(default=0.0, help_text="<strong style='color:red;'>This shoulg be a percentage of the amount the user buys</strong>"),
        ),
        migrations.AddField(
            model_name='cablerecharegapi',
            name='htoken',
            field=models.CharField(default='Basic cGF1bHByb21pc2UyMDBAZ21haWwuY29tOkdldHVwQDQ0NA', help_text='this should be a unique identifier', max_length=100),
        ),
        migrations.AddField(
            model_name='cablerecharegapi',
            name='provider',
            field=models.CharField(default='https://example.com', max_length=1000),
        ),
        migrations.AddField(
            model_name='cablerecharegapi',
            name='referrer_bonus',
            field=models.FloatField(default=0.0, help_text="<strong style='color:red;'>This shoulg be a percentage of the amount the user buys</strong>"),
        ),
        migrations.AddField(
            model_name='cablerecharegapi',
            name='service_id',
            field=models.CharField(default='waec_airtime', help_text='this should be a unique identifier', max_length=50),
        ),
        migrations.AddField(
            model_name='cablerecharegapi',
            name='user_discount',
            field=models.FloatField(default=0.0, help_text="<strong style='color:red;'>This shoulg be a percentage of the amount the user buys</strong>"),
        ),
        migrations.AddField(
            model_name='cablerecharegapi',
            name='vtoken',
            field=models.CharField(default='Basic cGF1bHByb21pc2UyMDBAZ21haWwuY29tOkdldHVwQDQ0NA', help_text='this should be a unique identifier', max_length=100),
        ),
        migrations.AlterField(
            model_name='cablerecharegapi',
            name='identifier',
            field=models.CharField(default='startimes', help_text='this should be a unique identifier', max_length=50),
        ),
    ]
