# Generated by Django 5.0.6 on 2024-08-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_remove_cablerecharegapi_api_url_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cablerecharegapi',
            name='htoken',
            field=models.CharField(default='Basic XXXXXXXXXXX', help_text='this should be a unique identifier', max_length=100),
        ),
        migrations.AlterField(
            model_name='cablerecharegapi',
            name='vtoken',
            field=models.CharField(default='Basic XXXXXXXXXX', help_text='this should be a unique identifier', max_length=100),
        ),
    ]
