# Generated by Django 5.0.6 on 2024-08-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=250)),
                ('secret_key', models.CharField(max_length=250)),
                ('activation_url', models.CharField(max_length=250)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
    ]
