# Generated by Django 5.0.6 on 2024-09-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationkeys',
            name='activation_url',
            field=models.CharField(max_length=300),
        ),
    ]
