# Generated by Django 5.0.6 on 2024-09-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_activationkeys_activation_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationkeys',
            name='secret_key',
            field=models.CharField(max_length=250),
        ),
    ]
