# Generated by Django 5.0.6 on 2024-09-08 02:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('paystack_charge', models.DecimalField(decimal_places=3, default=Decimal('0.016'), help_text='Enter the Paystack charge percentage. (e.g., 1.6 for 1.6%)', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PaystackTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('wallet_before', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('wallet_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
