# Generated by Django 5.0.6 on 2024-08-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystacktransaction',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
