# Generated by Django 5.0.6 on 2024-08-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0002_paystacktransaction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('paystack_charge', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
