# Generated by Django 5.0.6 on 2024-08-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0003_paystackconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystackconfiguration',
            name='paystack_charge',
            field=models.DecimalField(decimal_places=2, help_text='Enter the Paystack charge percentage', max_digits=5),
        ),
    ]
