# Generated by Django 5.0.6 on 2024-08-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0004_alter_paystackconfiguration_paystack_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystacktransaction',
            name='wallet_after',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paystacktransaction',
            name='wallet_before',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paystackconfiguration',
            name='paystack_charge',
            field=models.DecimalField(decimal_places=4, help_text='Enter the Paystack charge percentage. (e.g., 1.6 for 1.6%)', max_digits=5),
        ),
    ]
