# Generated by Django 5.0.6 on 2024-08-02 22:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0005_paystacktransaction_wallet_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystackconfiguration',
            name='paystack_charge',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.016'), help_text='Enter the Paystack charge percentage. (e.g., 1.6 for 1.6%)', max_digits=5),
        ),
    ]
