# Generated by Django 5.0.6 on 2024-09-07 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('identifier', models.CharField(default='', max_length=50)),
                ('bill_type', models.CharField(blank=True, max_length=500, null=True)),
                ('bill_code', models.CharField(blank=True, max_length=500, null=True)),
                ('bill_number', models.CharField(blank=True, max_length=300, null=True)),
                ('bill_serial', models.CharField(blank=True, max_length=500, null=True)),
                ('bill_provider', models.CharField(blank=True, max_length=500, null=True)),
                ('actual_amount', models.FloatField(default=0.0)),
                ('paid_amount', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('old_balance', models.FloatField(default=0.0)),
                ('new_balance', models.FloatField(default=0.0)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('reference', models.CharField(blank=True, max_length=300, null=True)),
                ('customernumber', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('customername', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_dt_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('api_id', models.IntegerField(blank=True, null=True)),
                ('amtcredited', models.FloatField(blank=True, null=True)),
                ('api_response', models.TextField(blank=True, max_length=20000, null=True)),
                ('callback_url', models.TextField(blank=True, max_length=20000, null=True)),
                ('callback_done', models.BooleanField(default=False)),
                ('mode', models.CharField(default='DIRECT', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smsangosbulkcredit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_funding', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
