"""
Django settings for paytev project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5#25+gfyej#zyow-a-ph9vpp53m93-u1v9u_z)bhq!w=vwh6oh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'severely-model-ghost.ngrok-free.app',  
    'test.paytev.com',
    '67.223.118.123',
    "paytev.onrender.com"
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'account',
    'django_select2',
    'airtime_recharge',
    'alert_system',
    'paystack',
    'transactions',
    'bills',
    'flutterwave',
    'corsheaders',
    'strowallet',
    'monnify',
    'kyc',
    'emails',
]

FLUTTERWAVE_PUBLIC_KEY = 'FLWPUBK-2c58027b9826fa2234943a4b1dcfda7f-X'
FLUTTERWAVE_SECRET_KEY = 'FLWSECK-2112ee370e262c240731273cea72b410-18efa892c5evt-X'
#FLUTTERWAVE_BASE_URL = 'https://api.flutterwave.com/v3/payments'
#FLUTTERWAVE_TEST_KEY = 'FLWSECK_TEST-3182d8228a37115bafba2cf34eba175c-X'



# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Replace with your broker URL
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # Replace with your broker URL








MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'my_helper.middleware.simpleMiddleware'
    
]

ROOT_URLCONF = 'paytev.urls'


STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'account.context_processors.app_info',
            ],
        },
    },
]


WSGI_APPLICATION = 'paytev.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

#DATABASES = {
 #   'default': {
  #      'ENGINE': 'django.db.backends.mysql',
   #     'NAME': 'tivahubc_demo',
    #    'USER': 'tivahubc_demo',
     #   'PASSWORD': '};@]BF=n*U4g',
      #  'HOST': 'localhost', 
       # 'PORT': '3306', 
    #}
#}



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'main/static')

#STATIC_URL = '/static/'
#STATICFILES_DIRS = [
#    BASE_DIR / "static",
#]


MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'debug.log'),
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'paytev': {  # Replace 'your_app_name' with your actual app name
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}




#LOGGING = {
 #   'version': 1,
  #  'disable_existing_loggers': False,
   # 'handlers': {
    #    'console': {
     #       'level': 'DEBUG',
      #      'class': 'logging.StreamHandler',
       # },
        #'file': {
         #   'level': 'DEBUG',
          #  'class': 'logging.FileHandler',
           # 'filename': os.path.join(BASE_DIR, 'strowallet_webhook.log'),
#        },
 #   },
  #  'loggers': {
   #     'django': {
    #        'handlers': ['console', 'file'],
     #       'level': 'DEBUG',
      #      'propagate': True,
       # },
        #'strowallet': {
         #   'handlers': ['console', 'file'],
          #  'level': 'DEBUG',
           # 'propagate': False,
 #       },
  #  },
#}




AUTH_USER_MODEL = 'account.CustomUser'


PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]


AUTHENTICATION_BACKENDS = [
    'account.backends.InactiveUserBackend',
    'django.contrib.auth.backends.ModelBackend',  # Keep the default backend for active users
    'account.backends.CaseInsensitiveModelBackend',
]


CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",  # or the URL of your frontend application
    "http://127.0.0.1:8000",
    'https://severely-model-ghost.ngrok-free.app',
    'https://test.paytev.com', 
]

CORS_ALLOW_ALL_ORIGINS = True




# Email configuration
#EMAIL_BACKEND = 'paytev.custom_email_backend.CustomEmailBackend'



#django.core.mail.backends.smtp.EmailBackend
#EMAIL_BACKEND = 'paytev.custom_email_backend.CustomEmailBackend'
#django.core.mail.backends.console.EmailBackend
# Email configuration
EMAIL_BACKEND = 'paytev.custom_email_backend.CustomEmailBackend'
EMAIL_HOST = 'paytev.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = 'test@paytev.com'
EMAIL_HOST_PASSWORD = 'Ze-O%GJ$*1py'
DEFAULT_FROM_EMAIL = 'test@paytev.com'




# OTP settings
OTP_EXPIRATION_MINUTES = 15


