# Generated by Django 5.0.6 on 2024-08-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strowallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strowalletconfig',
            old_name='api_key',
            new_name='public_key',
        ),
    ]
