# Generated by Django 5.0.6 on 2024-08-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strowallet', '0002_rename_api_key_strowalletconfig_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hooklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myhook', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
