# Generated by Django 5.0.6 on 2024-08-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc_charge_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'KYC Settings',
                'verbose_name_plural': 'KYC Settings',
            },
        ),
    ]
