# Generated by Django 5.0.6 on 2024-07-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtime_recharge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('network_image', models.ImageField(blank=True, null=True, upload_to='network_images/')),
            ],
        ),
    ]
