# Generated by Django 5.0.6 on 2024-07-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtime_recharge', '0002_networkconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetworkConfiguration',
        ),
        migrations.AddField(
            model_name='airtimeapiconfiguration',
            name='network_id',
            field=models.CharField(default='1', help_text='Network identifier for API', max_length=50),
        ),
        migrations.AddField(
            model_name='airtimeapiconfiguration',
            name='network_name',
            field=models.CharField(default='MTN', help_text='Network name for display', max_length=50),
        ),
        migrations.AlterField(
            model_name='airtimeapiconfiguration',
            name='api_data',
            field=models.JSONField(default=dict, help_text='e.g: copy and paste this => {"data": {"serviceID": "mtn", "amount": "amount_float", "phone": "phone_number", "request_id": "request_id"}, "headers": {"Authorization": "Basic UHJpbmNlb295ZXNAZ21haWwuY29tOjFQYXl0ZXZUZWFt"}}'),
        ),
        migrations.AlterField(
            model_name='airtimeapiconfiguration',
            name='identifier',
            field=models.CharField(default='mtn_airtime', help_text='this should be a unique identifier', max_length=50),
        ),
        migrations.AlterField(
            model_name='airtimeapiconfiguration',
            name='network_image',
            field=models.ImageField(default='', help_text='the best image needed here is a square image recommended is 500 x 500', upload_to='network_images/'),
        ),
        migrations.AlterField(
            model_name='airtimeapiconfiguration',
            name='success_code',
            field=models.CharField(default='true', max_length=500),
        ),
    ]
