# Generated by Django 5.0.6 on 2024-07-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtime_recharge', '0003_delete_networkconfiguration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airtimeapiconfiguration',
            name='network_id',
        ),
        migrations.AddField(
            model_name='airtimeapiconfiguration',
            name='network_identifier_code',
            field=models.CharField(default='1', help_text='The network code or identifier (ID) used by the API', max_length=50),
        ),
    ]
